Column transformation in pandas

In [1]:
import pandas as pd

Rows and column selection

In [5]:
sdata=pd.read_csv("subdata_pandas/student.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [ ]:
# To select columns 
sdata[['firstName','fees','age','marks']]

# To select details based on column name withe condition
sdata.loc[sdata.firstName=="Nisha"]
sdata.loc[sdata.fees>=30000]

# Slicing on the rows
sdata.loc[1:5]  # 1=starting index, 5= ending index. i.e 1 to 5 index records will be displayed

#Slicing on both rows and columns
sdata.iloc[:4,:3]
sdata.iloc[2:7,1:4] # similar to slicing 2=start row 7-1=end row , 1=start col 4-1=end col

  firstName  lastName  age
2     Rohit  Bhandary   19
3     Nisha   D'Souza   20
4   Karthik   Poojary   22
5    Shreya    Shetty   19
6     Rohan      Naik   21

Filter

In [18]:
sdata['age']>=20        # boolean
std_age_filter=sdata[sdata['age']>20]  #values
std_age_filter

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [28]:
sdata.where(sdata['age']>20,"Minor") 
sdata.where(sdata['age']>20,other="Minor")
sdata.loc[(sdata['marks']>=85,"result")]="selected"
sdata.loc[(sdata['marks']<85,"result")]="Not_selected"
sdata

    id firstName  lastName  age  marks   fees        result
0  101    Akshay    Shetty   20     85  25000      selected
1  102    Ananya       Rao   21     92  30000      selected
2  103     Rohit  Bhandary   19     76  28000  Not_selected
3  104     Nisha   D'Souza   20     88  25000      selected
4  105   Karthik   Poojary   22     69  32000  Not_selected
5  106    Shreya    Shetty   19     95  30000      selected
6  107     Rohan      Naik   21     72  27000  Not_selected
7  108   Deepika      Bhat   20     81  28000  Not_selected
8  109  Abhishek    Kotian   22     64  26000  Not_selected
9  110     Pooja       Rai   19     90  30000      selected

In [30]:
sdata["fullname"]=sdata["firstName"]+" "+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees        result         fullname
0  101    Akshay    Shetty   20     85  25000      selected    Akshay Shetty
1  102    Ananya       Rao   21     92  30000      selected       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000  Not_selected   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000      selected    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Not_selected  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000      selected    Shreya Shetty
6  107     Rohan      Naik   21     72  27000  Not_selected       Rohan Naik
7  108   Deepika      Bhat   20     81  28000  Not_selected     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Not_selected  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000      selected        Pooja Rai