Dealing with duplicate values missing data

In [2]:
import pandas as pd
import numpy as np

In [3]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

Duplicate values

In [5]:
#Overall duplicte
cdata.duplicated()          #boolean value
cdata[cdata.duplicated()]   #select row
#Based on
cdata['id'].duplicated()    #op in boolean
cdata[cdata['id'].duplicated()] 
cdata.drop_duplicates()         # Overall duplicate delection(considering entire column matching)
cdata['id']=cdata['id'].drop_duplicates()   # based on employee id

Missing data

In [ ]:
# Checking null values in the small dataset 
cdata.isnull()

# Checking null values in the larger dataset 
cdata.isnull().sum()
'''
op:
id                      0
gender                  0
dateofbirth             1
education               0
department              0
salary                  0
starting_salary         0
job_time                0
previous_experience    25
minority                3
dtype: int64
'''
cdata['id'].isnull()

# Eliminate the Nan values
cdata.dropna()

# replace Nan with any values
cdata.replace(np.nan,"not_available") # op: 0 1	Male 03-02-1952	15	IT	57000 27000	8.17 not_available	No

# replacing nan with 3 in previous experiance
cdata['previous_experience']=cdata['previous_experience'].replace(np.nan,3)
cdata
# Replace nan salary with avg
mean=np.mean(cdata['salary'])
mean

#replacing mean by average
# method 1
cdata['salary']=cdata['salary'].replace(np.nan,34419)
cdata

#method 2
cdata['salary']=cdata['salary'].fillna(mean)
cdata

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,3.00,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [ ]:
# Forward fill
cdata.ffill() #ex: 1 n 3 ; 2 Nan 4 then op: 1 n 3 ; 2 n 4

#Backward fill
cdata.bfill() #x: 1 n 3 ; 2 Nan 4 ; 3 i 5 then op: 1 n 3 ; 2 i 4 ; 3 i 5

cdata.bfill(inplace=True)   # only in workspace not in og file 

cdata['salary']=cdata['salary'].bfill() # to change perticular field